#!/bin/bash
#########################################################################################################
##
## Name:            make_sdcard.sh
## Created:         August 2018
## Author(s):       Philip Smart
## Description:     Sharp MZ series SD Card Packaging tool
##                  This is a very basic script to package programs into images for writing onto an
##                  SD Card as used in the Rom Filing System. The image is comprised of several parts,
##                  ie. <RFS IMAGE> + <CPM DISK IMAGE 0> .. <CPM DIK IMAGE n>.
##
## Credits:         
## Copyright:       (c) 2020 Philip Smart <philip.smart@net2net.org>
##
## History:         March 2020   - Initial script written.
##                  March 2021   - Updated the file list.
##
#########################################################################################################
## This source file is free software: you can redistribute it and#or modify
## it under the terms of the GNU General Public License as published
## by the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This source file is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
#########################################################################################################

ROOTDIR=../../MZ80A_RFS
MZF_PATH=${ROOTDIR}/software/MZF
TOOL_DIR=${ROOTDIR}/software/tools
IMAGE_DIR=${ROOTDIR}/software/roms
CPM_DIR=${ROOTDIR}/software/CPM/SDC16M/RAW
SDTOOL=${TOOL_DIR}/sdtool
RFS_IMAGE_FILE=${IMAGE_DIR}/SHARP_MZ80A_RFS_IMAGE_1.img
CPM_IMAGE_FILES="SDCDISK0.RAW SDCDISK1.RAW SDCDISK2.RAW SDCDISK3.RAW SDCDISK4.RAW SDCDISK5.RAW SDCDISK6.RAW"
SD_IMAGE_FILE=${IMAGE_DIR}/SHARP_MZ80A_RFS_CPM_IMAGE_1.img
ROM_LIST_FILE=/tmp/ROMLIST

# Create the initial RFS image.
${SDTOOL} --image ${RFS_IMAGE_FILE} --create
if [ $? != 0 ]; then
    echo "Failed to create initial RFS Image, aborting."
    exit 1
fi

# Manually choose the programs you want installed into the RFS image. The files will be first placed into
# the directory in the order they appear here, which initially is alphabetic order.
#
# NB: A maximum of 256 files can be added due to the limit of the RFS directory.
#
RFS_INCLUDE=
#
# Current Common files.
#
RFS_INCLUDE+="${MZF_PATH}/Common/BASIC.MZF:"
RFS_INCLUDE+="${MZF_PATH}/Common/CPM223.MZF:"
RFS_INCLUDE+="${MZF_PATH}/Common/cpm22.MZF:"
RFS_INCLUDE+="${MZF_PATH}/Common/SEND-1.MZF:"
RFS_INCLUDE+="${MZF_PATH}/Common/sharpmz-test.MZF:"
RFS_INCLUDE+="${MZF_PATH}/Common/testtz.MZF:"
#
# MZ-80A files.
#
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/3-D_MAZE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/80A_PENCIL.A2_C2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/80A_PENCIL.A2_S.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/A-BASIC_SA-5510.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/ADVENTUREGAME.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/AIR_LANDER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/ALIEN_ATTACK_MACHINECODE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/ALIEN_ATTACK.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/ALIEN_EAGLE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/ALLIGATOR.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/APOLLO_CHESS_V2A.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/BASIC80A.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/BASIC_SA-5510.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/BASIC.SA-5510.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/BLOCKING.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/BOUNCING_BALL.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/BREAKOUT_MC.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/BREAKOUT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/BRICKSTOP.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/BYTESAVER_SA5510.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/CELLS_AND_SERPS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/COLONY.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/COSMIAD-A.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/COSMIAD-K.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/CURSEDCHAMBER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/DCS_MZ80A_APPEND.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/DCS_MZ80A_RENUM.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/DEFENDER(2).MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/DEFENDER_BIZZARRI.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/DEFENDER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/DIAMOND.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/DIGGER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/DOG_AND_FLEA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/DOG_STAR_2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/DUCK_SHOOT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/EPIDEMIC.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/ESCAPE_FORCE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/ESCAPE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/FLYING_MISSION.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/FOREST_OF_DOOM.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/FRUIT_MACHINE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/GALAXY_INVADERS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/GREEDY_GREMLINS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/HANGMAN2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/HORSE_RACE2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/HUCALC_80A_C2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/HUCALC_80A_M.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/HUCALC_80A_S.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/LAND_ESCAPE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/LASER_DEFENCE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/LE_MANS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/LUDO.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/LUNARLANDER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/MAD_MAX_2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/MAN-HUNT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/M_C_BREAKOUT_2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/M_C_RACE_CHASE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/MINOTAUR.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/MISSILE_ATTACK.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/MUNCHERS_2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/MZ80A_BASIC.DSK:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/MZ-80A_GALACTIC.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/NAVVY.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/NEW_INVADERS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/NOUGHTS_CROSSES.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/NUMBERCRUNCH.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/OBSTACLES.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/PINBALL.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/PUCKMAN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/QBERT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/QUEST.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/RACE_CHASE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/RIBBIT_V2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SA-5510_COMPILER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SA-5510_KN.COMM.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SA-6510.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SARGON_2.71.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SCRAMBLE_A.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SERENDIPITY.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SKI_RUN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SPACE_COMBAT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SPACE_FIGHTER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SPACE_INVADERS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SPOOKS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/STARSHIP_MK2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/STAR_WARS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/SUPER_TILT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/THE_LILY_POND.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/THE_MEANIES.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/TUNNEL_RUN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/UFO.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/WIGGLY_WORM.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/WITCHES.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-80A/XPATCH_5510_V2.2.MZF:"
#
# MZ-700 files.
#
RFS_INCLUDE+="${MZF_PATH}/MZ-700/1Z-013B.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/2Z009E.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/3-D_CAR_RACE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/3-D_GRAPHIKPAKET.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/3DMUEHLE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/3D-WAY_OUT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/6502_BETRIEBSSYS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/700_POKER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ACE_RACER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ADVANCEDCHESS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/AIRBUS_A_310.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ALIENS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/AMITYVILLE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ANTARES.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ANTHILL_RAIDER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/APOLLO2_8-200785.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/APOLLO.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/APPRENTISSAGE_NOMBRES.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ASTEROID_BELT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ASTRO-BLASTER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ATTACK-A-TANK.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/AUTO_RUN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BACKGAMMON.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BAS700TUTORIAL.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BASEZERO.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BASIC_1Z-013B.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BASIC_700-VERS.4.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BASIC_MZ-5Z008_2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BASIC_MZ-5Z008.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BATTLE_GAME.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BIO-700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BLASTOFF.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BLOKTEKENINGEN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BOMBERMAN_MZ700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BOULDER_DASH.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/BREUKEN_1.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CADRE_DIABOLIQUE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CALENDRIER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CANNON_BALL.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CATACOMBES.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CATERPILLAR.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CENTRO-ANL.DISK.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CENTRO-ANLEITUNG.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CIRCUS_STAR.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CLUB_GOLF.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/C-MASTER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CODEWOORD.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/COMMANDO_PLAIN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/COMPETITIE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/COMPUT-A-SLOT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/COMPUTERTEKENEN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CONNECT_FOUR.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CONVERTER_A_700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CONVEYOR.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/COPY-CF.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/COSMO_BLASTER_MZ700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CRIBBAGE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CROAKER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/CYFAX.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/DATABASE_FILER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/DATEI_UNIVERSAL.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/DBP-701.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/DELETE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/DEMASASO.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/DEMO-LISSAJOU.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/DEMO_SIN-BERG.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/DESCENTE_AUX_ENFERS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/DESTRUCTEURS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/DOMINATION.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/DONKEY_GORILLA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/EXPLODING_ATOMS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/EXPRESS_BAS_700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/F1200.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/FANTASTIC_GROVE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/FDCOPY.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/FD_EDITOR_MZ700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/FIGHTER_COMMAND.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/FIRE!!!.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/FISHERMAN_FRED.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/FLUGSIM_MZ700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/FLUGSIMULATOR.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/FORTRANSOSZ80.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/FULL_SPEED.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/GATE-CRASHER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/GDP9-BA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/GEBOORTEDATUM.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/GLOBAL_WAR_3.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/GLOBULE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/GOBBLER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/GREEDY_GREMLINS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/GRID.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/GUERRE_SPATIALE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/HDC_ORGEL.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/HP4TMZ7L.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/HP4TMZ7.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/HUNCHY.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/IMPOSSIBLE_MISSION.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ISOLA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/JEUX_INTERGALACTIQUES.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/JUMPING_RUNNER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/JUNGLE-JINKS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/KALENDER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/KAMERTJE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/KASBOEK.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/K-BASIC_V.5.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/KENTUCKY_DERBY.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/KNIFORTH.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/KNIGHT'S_CASTLE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/KNIGHTS_UFO.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/KP_DBASIC.800B.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/K.S.M._PT._1.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/K.S.M._PT._2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/K.S.M._PT._3.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/KUMA_INTERPR..MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/KUP80Z354.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/KUP80Z355.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/LADY-BUG.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/LAND_ESCAPE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/LE_MANS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/LIGHTNING_PATROL.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/LIJNENSPEL.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/LOGO_V30.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MAC_PAC.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MAD_MAZE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MAN-HUNT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MANZA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MASTERMIND.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MATH_PENDU.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MAZE_ESCAPE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MESSING.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MISSION_ALPHA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MISSION_A.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MISSION_DELTA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ML-SP_8002_BBG.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MOLEATTA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MONITOR3.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MONITOR6.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MONITOR.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MORPION.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MORPIUS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MOTY.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MOVING_SEARCHER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MUCMAC700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MUNROE_MANOR.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MUSIC.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MUSIQUE_SUISSE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MZ-1P01.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MZ-2Z009.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MZ700BAS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MZ-700_DEMO.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MZ700_FORTH1.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MZ-700_FORTH.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MZ-700_KLAVIER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/MZ-700_PLOT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/NAKAMOTO_MZ700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/NAKAMOTO.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/NIBBLER_PART1.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/NIBBLER_PART2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/NIGHTMARE_PARK2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/NIGHTMARE_PARK.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/NIGHTM_PRK.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/NITE_FLITE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/OCTOPUSSY.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PAC-MAN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PAINFUL_MAN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PANIQUE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PARA_SHOOT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PASCAL_SP-4015_C.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PASCAL_SP-4015.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PATROL_ALPHA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PCGAID_EUROPE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PCGAID.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PCG_BASIC_MZ700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PCG_BASIC.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PENDU.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PRINTERFIGUREN1.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PUISSANCE_4.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/PUZZLE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/QD_BAS_5Z008_MZ700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/QDCOPY.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/QD-PASCAL_C.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/QUIXI.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/REALFORT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/REBOND.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/RESCUE_PLANE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/REVERSE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ROLLSROYCE1906.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ROUND_SHOOT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SAFE-CRACKER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/S-BASIC-CENT-2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/S-BASIC-COMP-CNT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/S-BASIC-COMPILER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/S-BASIC-COMPILER-ORIGINAL.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/S-BASICODE_2.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SCHACH2_MZ700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SCHACH700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SH7CED1.3G.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SHOGUN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SKY_CHAOS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/S-MASTER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SNAKE-AND-SNAKE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SOUDARD.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SOUTH_PACIFIC.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SPACE_FIGHTER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SPACE_GUERILLA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SPACE_INVADERS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SPA_DATA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SQUASH_700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/STAR_FIGHTER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/STARTREK.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/STKEEPER2BAS700A.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/STRIP_POKER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUBMARINE_SHOOTER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUB-MONITOR-700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUICIDE_RUN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUPER-BANDIT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUPER_BIORHYTHM.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUPER_HELICOPTER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUPER_PUCK-MAN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUPER_SPY_OBJ.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUPERTYPEN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUPER_VRAC.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUTAM1F.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUTAMC9.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUTAPEBA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SUTAPEMO.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/SYSTEME_EXPERT.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/TAPEWORM.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/TBASIC_BM_PK.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/T-BASIC_(UITLEG).MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/TELEFONTARIEVEN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/THREE_CARD_BRAG.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/TOMAHAWK.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/TRACKER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/TRANS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/TRUCKER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/TYPEN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/UFO.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/UNI700BASIC.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/URANIA_II.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/URAS-700.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/VICIOUS_VIPER.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/VOL_676.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/VRAGENDMAKEN.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/WIZARD_CASTLE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/WONDERHOUSE.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/WOOKYA.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/WOOKYB.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/XANAGRAMS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/XBC_F_1_02.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/XBC.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/YAMS.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/Z80_DESASSEMBLEUR.MZF:"
RFS_INCLUDE+="${MZF_PATH}/MZ-700/ZEN.MZF:"
#
#
#
IFS=":"; for f in ${RFS_INCLUDE}
do
    # Use the ROM File List to filter out duplicates.
    #
    grep `basename "${f}" .MZF` ${ROM_LIST_FILE} l > /dev/null
    if [ $? = 1 ]; then
	    echo "Adding ${f}..."
	    ${SDTOOL} --image ${RFS_IMAGE_FILE} --add ${f}
	    RESULT=$?
	    if [ $RESULT != 0 ]; then
		if [ $RESULT = 60 ]; then
		    break; 
		fi
		echo "Failed to add:${f} into the RFS Image, aborting."
		exit 2
	    fi
    fi
done
${SDTOOL} --image ${RFS_IMAGE_FILE} --list-dir

# Concatenate the RFS and CPM images to make a final SD card image.
#
echo "Adding RFS Image:$RFS_IMAGE_FILE} to start of SD Card image."
cat ${RFS_IMAGE_FILE} > ${SD_IMAGE_FILE}
IFS=" "; for f in ${CPM_IMAGE_FILES}
do
    echo "Adding CPM Drive Image:${f} to SD Card image."
    cat ${CPM_DIR}/${f} >> ${SD_IMAGE_FILE}
done
echo "SD Card image generated, file:${SD_IMAGE_FILE}"

exit 0
