#!/bin/bash
#########################################################################################################
##
## Name:            make_roms.sh
## Created:         August 2018
## Author(s):       Philip Smart
## Description:     Sharp MZ series Flash ROM Packaging tool
##                  This is a very basic script to package programs into ROM images suitable for
##                  programming into the Flash ROMS. It needs a rewrite but for now please
##                  manually edit the list below to select the programs you want, run the script
##                  and flash the images created into the Flast ROMS.
##
## Credits:         
## Copyright:       (c) 2020-21 Philip Smart <philip.smart@net2net.org>
##
## History:         January 2020   - Initial script written.
##                  March 2021     - Updates for the RFS v2.1 board.
##                  April 2021     - Removed the CPM ROM Drive functionality as it provided no benefit
##                                   over SD card and SD cards are larger.
##
#########################################################################################################
## This source file is free software: you can redistribute it and#or modify
## it under the terms of the GNU General Public License as published
## by the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This source file is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
#########################################################################################################

ROOTDIR=../../MZ80A_RFS
MZB_PATH=${ROOTDIR}/software/MZB
ROM_PATH=${ROOTDIR}/software/roms/
ROM_LIST_FILE=/tmp/ROMLIST
SECTORSIZE=256
#CPMDISKMODE=SPLIT
MZFTOOL=${ROOTDIR}/software/tools/mzftool.pl
MONITOR_ROM=/tmp/mrom.rom
USER_ROM_I=/tmp/user.rom
USER_ROM_II=/tmp/user2.rom
USER_ROM_III=/tmp/user3.rom

# Monitor/User ROM 1/2/3 = empty.
> ${MONITOR_ROM}
> ${USER_ROM_I}
> ${USER_ROM_II}
> ${USER_ROM_III}

# Create a file with a list of programs placed into the ROM. This list can then be used by the SD
# card script to ensure no duplication occurs when building the SD RFS program directory.
rm -f ${ROM_LIST_FILE}

# Place the monitor roms into the MROM at the beginning for banked page usage.
echo "cat ${ROM_PATH}/monitor_SA1510.rom ${ROM_PATH}/monitor_80c_SA1510.rom  ${ROM_PATH}/cbios.rom ${ROM_PATH}/rfs_mrom.rom ${ROM_PATH}/monitor_1Z-013A.rom ${ROM_PATH}/monitor_80c_1Z-013A.rom ${ROM_PATH}/IPL.rom ${ROM_PATH}/blank_mrom.rom > /tmp/mrom.rom"
cat ${ROM_PATH}/monitor_SA1510.rom ${ROM_PATH}/monitor_80c_SA1510.rom \
    ${ROM_PATH}/cbios.rom ${ROM_PATH}/rfs_mrom.rom \
    ${ROM_PATH}/monitor_1Z-013A.rom ${ROM_PATH}/monitor_80c_1Z-013A.rom \
    ${ROM_PATH}/IPL.rom ${ROM_PATH}/blank_mrom.rom \
    >> ${MONITOR_ROM}

# Place the RFS rom into the User ROM at the beginning as it contains all the banked pages.
echo "cat ${ROM_PATH}/rfs.rom ${ROM_PATH}/cbios_bank1.rom ${ROM_PATH}/cbios_bank2.rom ${ROM_PATH}/cbios_bank3.rom ${ROM_PATH}/cbios_bank4.rom > ${USER_ROM_I}"
cat ${ROM_PATH}/rfs.rom ${ROM_PATH}/cbios_bank1.rom ${ROM_PATH}/cbios_bank2.rom \
    ${ROM_PATH}/cbios_bank3.rom ${ROM_PATH}/cbios_bank4.rom \
    >> ${USER_ROM_I}

# For CPM, to be safe, we manually copy the required files rather than use the list below. The CP/M boot image must be in User ROM 1.
cat ${MZB_PATH}/Common/cpm22.${SECTORSIZE}.bin >> ${USER_ROM_I}

# According to flag set above, either put the CPM Disks in the first ROM, or place one in each ROM allowing for better write spread and larger disks.
#
#if [ "${CPMDISKMODE}" != "SPLIT" ]; then
#    # CPM RFS Disks currently only in User ROM.
#    for f in 1 2
#    do
#        if [ -f ${MZB_PATH}/Common/CPM_RFS_${f}.${SECTORSIZE}.bin ]; then
#            echo "cat ${MZB_PATH}/Common/CPM_RFS_${f}.${SECTORSIZE}.bin >> ${USER_ROM_I}"
#            cat ${MZB_PATH}/Common/CPM_RFS_${f}.${SECTORSIZE}.bin >> ${USER_ROM_I}
#            basename "${f}" .${SECTORSIZE}.bin >> ${ROM_LIST_FILE}
#        fi
#    done
#else
#    if [ -f ${MZB_PATH}/Common/CPM_RFS_1.${SECTORSIZE}.bin ]; then
#        echo "cat ${MZB_PATH}/Common/CPM_RFS_1.${SECTORSIZE}.bin >> ${USER_ROM_I}"
#        cat ${MZB_PATH}/Common/CPM_RFS_1.${SECTORSIZE}.bin >> ${USER_ROM_I}
#        basename "${f}" .${SECTORSIZE}.bin >> ${ROM_LIST_FILE}
#    fi
#
#    if [ -f ${MZB_PATH}/Common/CPM_RFS_2.${SECTORSIZE}.bin ]; then
#        echo "cat ${MZB_PATH}/Common/CPM_RFS_2.${SECTORSIZE}.bin >> ${USER_ROM_II}"
#        cat ${MZB_PATH}/Common/CPM_RFS_2.${SECTORSIZE}.bin >> ${USER_ROM_II}
#        basename "${f}" .${SECTORSIZE}.bin >> ${ROM_LIST_FILE}
#    fi
#fi

# Manually choose the programs you want installed into the ROMS. The files will be first placed into the USER ROM and when full into the 
# Monitor ROM. Thus order is important if you want a particular program in a particular ROM.
#
# NB: A Double Hash (##) indicates a program found not to work on the Sharp MZ-80A.
#
ROM_INCLUDE=""
#
# Common
#
ROM_INCLUDE+="${MZB_PATH}/Common/SA-5510_RFS.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/BASIC_SA5510.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/BASIC_SA6510.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/MSBASIC_MZ80A.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/MSBASIC_RFS.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/SA-5510_COMPILER.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/BAS_MOD_V374.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/XPATCH_5510_V2.2.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/BASIC_SP5025.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/BASIC_SP5030.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/BASIC_SP-5035MC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/SOLO_BASIC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/BASIC_OM-500.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/BASIC_OM-1000.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/BASIC_OM-1001.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/HU-BASIC_V1.3_K.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/HUCOMPILMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/COMPILER_A2.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/EXPRESS_COMPILER.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/K_A_CONVERTER.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/HISOFT_PASCAL4.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/Z80ASSEMBLER2MC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/EDITOR-ASSEMBLER_SP2202MC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/ZEN.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/8048_CPU_DISAS.MC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/6502BETRMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/6502DEMO2MC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/6502DEMOMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/FORTRANSOSZ80.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/MZ700_FORTH1.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/KNIFORTH.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/TINYLISPMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/APOLLO_WORD_1.9MMC_.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/HUCALC_80A_M.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/SEND-1.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/Common/APOLLO_CHESS_V2A.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/Common/5Z009-1B.MZF:"
#ROM_INCLUDE+="${MZB_PATH}/Common/BASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/Common/cpm22.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/Common/CPM223.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/Common/sharpmz-test.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/Common/testtz.${SECTORSIZE}.bin:"
#
# MZ-80A
#
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SA-6510.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/3-D_MAZE.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/80A_PENCIL.A2_C2.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/80A_PENCIL.A2_S.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/A-BASIC_SA-5510.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/ADVENTUREGAME.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/AIR_LANDER.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/ALIEN_ATTACK.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/ALIEN_ATTACK_MACHINECODE.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/ALIEN_EAGLE.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/ALLIGATOR.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/APOLLO_CHESS_V2A.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/BASIC80A.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/BASIC_SA-5510.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/BASIC.SA-5510.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/BLOCKING.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/BOUNCING_BALL.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/BREAKOUT.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/BREAKOUT_MC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/BRICKSTOP.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/BYTESAVER_SA5510.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/CELLS_AND_SERPS.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/COLONY.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/COSMIAD-A.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/COSMIAD-K.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/CURSEDCHAMBER.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/DCS_MZ80A_APPEND.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/DCS_MZ80A_RENUM.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/DEFENDER(2).${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/DEFENDER.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/DEFENDER_BIZZARRI.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/DIAMOND.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/DIGGER.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/DOG_AND_FLEA.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/DOG_STAR_2.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/DUCK_SHOOT.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/EPIDEMIC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/ESCAPE.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/ESCAPE_FORCE.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/FLYING_MISSION.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/FOREST_OF_DOOM.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/FRUIT_MACHINE.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/GALAXY_INVADERS.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/GREEDY_GREMLINS.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/HANGMAN2.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/HORSE_RACE2.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/HUCALC_80A_C2.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/HUCALC_80A_M.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/HUCALC_80A_S.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/LAND_ESCAPE.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/LASER_DEFENCE.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/LE_MANS.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/LUDO.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/LUNARLANDER.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/MAD_MAX_2.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/MAN-HUNT.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/M_C_BREAKOUT_2.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/M_C_RACE_CHASE.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/MINOTAUR.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/MISSILE_ATTACK.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/MUNCHERS_2.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/MZ-80A_GALACTIC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/NAVVY.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/NEW_INVADERS.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/NOUGHTS_CROSSES.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/NUMBERCRUNCH.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/OBSTACLES.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/PINBALL.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/PUCKMAN.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/QBERT.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/QUEST.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/RACE_CHASE.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/RIBBIT_V2.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SA-5510_COMPILER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SA-5510_KN.COMM.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SARGON_2.71.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SCRAMBLE_A.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SEND-1.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SERENDIPITY.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SKI_RUN.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SPACE_COMBAT.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SPACE_FIGHTER.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SPACE_INVADERS.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SPOOKS.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/STARSHIP_MK2.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/STAR_WARS.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/SUPER_TILT.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/THE_LILY_POND.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/THE_MEANIES.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/TUNNEL_RUN.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/UFO.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/WIGGLY_WORM.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80A/WITCHES.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80A/XPATCH_5510_V2.2.${SECTORSIZE}.bin:"
#
# MZ-80K
#
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/3DSPACECBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/3-D_WAY_OUT_BBG_SOFTWARE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/6502BETRMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/6502DEMO2MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/6502DEMOMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/8048_CPU_DISAS.MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/A-BASIC_SA-5510.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ABENTEUEBASIC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ADVANCE-GUARDMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ADVANCE_GUARD_WICS_1983.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/AIMEMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ALIENMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ANDROMEDAMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/APOLLO_WORD_1.9MMC_.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ASCII_GAMEBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ATCF_DATAMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ATTACKERSCRAMBLEMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BARCODE_READER_1BASIC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BARCODE_READER_2BASIC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BARCODE_READER_3BASIC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BARCODE_READER_4BASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BASE_BALLBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BASEBALLBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BASIC_SP-5035MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BLOCK_KUZUSHIMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BOMBERBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BOMBERMAN_HUDSON_SOFT_1983.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BOUEISAKUSENBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BOXING_MZMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BREAKOUT_SHARP_CORPORATION.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BUGFIRE_1.1_WICS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BUGFIRE-NEWMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BUGFIRE-OLDMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/BUGFIRE_WICS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/CANNON_BALL_HUDSON_SOFT_1983.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/CAR-RACEMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/CLEVER_CRIBBER.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/CODE_HU_CONVERTMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/COSMIC_CRUISER1MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/COSMIC_CRUISER2MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/COSMIC_CRUISER3PR1MC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/COWBOY_DUELMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/CRAZY-CLIMBER_PT1MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/CRAZY-CLIMBER_PT2MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/CRYSTALLMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/DAIKAISENBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/D-DAY_SHARP_CORPORATION.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/DEFENDERMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/DEFEND_THE_CITYBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/DON_CHACKBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/DONKEY_DERBY.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/EDITOR-ASSEMBLER_SP2202MC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ELEKTRONIC_MUSICMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/EMPIRE_CLIMBERMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/EMPIRE_CLIMBER_WICS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/EXECUTIVEBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/F-1_RACEMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/FDCONTROMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/FILECARDMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/FORM_MAP-LISTMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/FORMMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/FORTH_SIMULATORBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/FORTRESSMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/GALACTICABASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/GALAXIANBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/GENS3_1MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/GOKIBURIBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/GOLDMINEBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/GOMOKUMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/HAT_THE_BOXBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/HOME_BUDGET_MK2BASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/HUCOMPILERMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/HUCOMPILMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/IDENTI-KIT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/JAMPACMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/JINTORIMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/JUMPING_BUNNYMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/LADYBUGMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/LASER_COMMANDMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/LOADERCKMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/LUNAR_LANDER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/LUNAR_LANDINGMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MACHINE_LANGUAGE_SP2001MC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MACHIN_LANG.MONMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MANNENBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MASTER_MINDBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MAZEMANMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MICROPEDEMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MINOTAUR'S_CAVEMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MIZ-MAZEBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MOGURABASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MONACO-GPMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MONITORMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MONITORRMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/MUNCHIESMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/NAUTIC_CRISISBASIC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/NEPTUNMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/NOTUTORIBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/NSC-RALLYMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ONE_KEY_ORGANMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/OTHELLOMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/OTORI_ATTACKMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/PACMANMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/PASCAL_SP-6610MC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/PHOENIXMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/PRINTMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/PUCKMANMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/RACEMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/RALLEYMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/RANGER_SPECIALPACMANMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SARGONCHESSMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SCASHBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SCHLOGESMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SCRAMBLE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SCRAMBLEMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SHOOTING-UFOBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SHOUGIBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_DEFENDERMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_DRIVESCRAMBLEMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_FIGHTER_SHARP_CORPORATION_1979.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_INVADER1MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_INVADER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_INVADER2INTRO-JPNMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_INVADER2NO_INTROMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_INVADER3MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_INVADER4MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE-INVADERMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_MOUSE2MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_MOUSEMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_MOUSE_WICS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_PANICMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_RUINERDEFFENDERMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPACE_RUINER_WICS_1982.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SPIDER_MAZE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/STARTREKBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/STAR_TREK_JPNBASIC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/STAR_TREK_SHARP_CORPORATION.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/STAR_WARSMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/STAR-WARSMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/STONEWORLDBASIC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SUB-MONITOR_48KMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SUPERDEFENDERMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SUPER-MONITORMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SUPERTARGMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SUPERWURMMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/SURVIVEMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TANKWARMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TAPECOPYMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TEN-PIN_BOWLING.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TEST_MATCH.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/THE_MUNCHIES_C_SMITH.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TIME_BOMBBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TINYLISPMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TOMAHAWK_HIROSHI_MASUKO.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TOMAHAWKMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TOWERINGMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TRAPMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TURTLEGDEMO1MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TURTLEGDEMO2MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TURTLE-GRAFIKMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/TYCOONBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/UBOOTJAGMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/UFO_CAVESMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/UFO_HUNTERMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/UNDAMESHIBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/VIDEOFLIPPERMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/VIEW-FINDERMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/VIEW_FINDER_WICS_1983.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/VIKINGMC.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-80K/VOICEMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/WAR_OF_CONBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/WESTERNMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/WESTERN_WICS_1983.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/WILHELM-TELLMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/WILLHELM_TELLMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/YAKYUKENBASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/Z80ASSEMBLER2MC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ZARDOSMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ZARDOS_MZ_SOFT_GROUP.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ZEICHENGMC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-80K/ZEROIDMC.${SECTORSIZE}.bin:"
#
# MZ-700
#
ROM_INCLUDE+="${MZB_PATH}/MZ-700/1Z-013B.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/2Z009E.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/3-D_CAR_RACE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/3-D_GRAPHIKPAKET.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/3DMUEHLE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/3D-WAY_OUT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/6502_BETRIEBSSYS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/700_POKER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ACE_RACER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ADVANCEDCHESS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/AIRBUS_A_310.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ALIENS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/AMITYVILLE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ANTARES.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ANTHILL_RAIDER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/APOLLO.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/APOLLO2_8-200785.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/APPRENTISSAGE_NOMBRES.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ASTEROID_BELT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ASTRO-BLASTER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ATTACK-A-TANK.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/AUTO_RUN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BACKGAMMON.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BAS700TUTORIAL.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BASEZERO.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BASIC_1Z-013B.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BASIC_700-VERS.4.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BASIC_MZ-5Z008_2.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BASIC_MZ-5Z008.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BATTLE_GAME.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BIO-700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BLASTOFF.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BLOKTEKENINGEN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BOMBERMAN_MZ700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BOULDER_DASH.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/BREUKEN_1.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CADRE_DIABOLIQUE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CALENDRIER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CANNON_BALL.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CATACOMBES.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CATERPILLAR.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CENTRO-ANL.DISK.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CENTRO-ANLEITUNG.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CIRCUS_STAR.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CLUB_GOLF.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/C-MASTER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CODEWOORD.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/COMMANDO_PLAIN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/COMPETITIE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/COMPUT-A-SLOT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/COMPUTERTEKENEN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CONNECT_FOUR.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CONVERTER_A_700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CONVEYOR.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/COPY-CF.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/COSMO_BLASTER_MZ700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CRIBBAGE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CROAKER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/CYFAX.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/DATABASE_FILER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/DATEI_UNIVERSAL.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/DBP-701.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/DELETE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/DEMASASO.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/DEMO-LISSAJOU.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/DEMO_SIN-BERG.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/DESCENTE_AUX_ENFERS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/DESTRUCTEURS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/DOMINATION.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/DONKEY_GORILLA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/EXPLODING_ATOMS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/EXPRESS_BAS_700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/F1200.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/FANTASTIC_GROVE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/FDCOPY.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/FD_EDITOR_MZ700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/FIGHTER_COMMAND.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/FIRE!!!.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/FISHERMAN_FRED.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/FLUGSIM_MZ700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/FLUGSIMULATOR.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/FORTRANSOSZ80.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/FULL_SPEED.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/GATE-CRASHER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/GDP9-BA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/GEBOORTEDATUM.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/GLOBAL_WAR_3.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/GLOBULE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/GOBBLER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/GREEDY_GREMLINS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/GRID.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/GUERRE_SPATIALE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/HDC_ORGEL.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/HP4TMZ7.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/HP4TMZ7L.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/HUNCHY.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/IMPOSSIBLE_MISSION.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ISOLA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/JEUX_INTERGALACTIQUES.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/JUMPING_RUNNER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/JUNGLE-JINKS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/KALENDER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/KAMERTJE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/KASBOEK.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/K-BASIC_V.5.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/KENTUCKY_DERBY.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/KNIFORTH.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/KNIGHT'S_CASTLE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/KNIGHTS_UFO.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/KP_DBASIC.800B.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/K.S.M._PT._1.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/K.S.M._PT._2.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/K.S.M._PT._3.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-700/KUMA_INTERPR..${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/KUP80Z354.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/KUP80Z355.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/LADY-BUG.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/LAND_ESCAPE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/LE_MANS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/LIGHTNING_PATROL.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/LIJNENSPEL.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/LOGO_V30.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MAC_PAC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MAD_MAZE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MAN-HUNT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MANZA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MASTERMIND.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MATH_PENDU.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MAZE_ESCAPE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MESSING.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MISSION_A.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MISSION_ALPHA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MISSION_DELTA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ML-SP_8002_BBG.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MOLEATTA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MONITOR.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MONITOR3.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MONITOR6.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MORPION.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MORPIUS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MOTY.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MOVING_SEARCHER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MUCMAC700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MUNROE_MANOR.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MUSIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MUSIQUE_SUISSE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MZ-1P01.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MZ-2Z009.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MZ700BAS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MZ-700_DEMO.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MZ700_FORTH1.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MZ-700_FORTH.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MZ-700_KLAVIER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/MZ-700_PLOT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/NAKAMOTO.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/NAKAMOTO_MZ700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/NIBBLER_PART1.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/NIBBLER_PART2.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/NIGHTMARE_PARK2.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/NIGHTMARE_PARK.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/NIGHTM_PRK.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/NITE_FLITE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/OCTOPUSSY.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PAC-MAN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PAINFUL_MAN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PANIQUE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PARA_SHOOT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PASCAL_SP-4015.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PASCAL_SP-4015_C.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PATROL_ALPHA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PCGAID.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PCGAID_EUROPE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PCG_BASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PCG_BASIC_MZ700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PENDU.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PRINTERFIGUREN1.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PUISSANCE_4.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/PUZZLE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/QD_BAS_5Z008_MZ700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/QDCOPY.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/QD-PASCAL_C.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/QUIXI.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/REALFORT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/REBOND.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/RESCUE_PLANE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/REVERSE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ROLLSROYCE1906.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ROUND_SHOOT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SAFE-CRACKER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/S-BASIC-CENT-2.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/S-BASIC-COMP-CNT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/S-BASIC-COMPILER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/S-BASIC-COMPILER-ORIGINAL.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/S-BASICODE_2.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SCHACH2_MZ700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SCHACH700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SEND-1.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SEND-1_MZ700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SH7CED1.3G.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SHOGUN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SKY_CHAOS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/S-MASTER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SNAKE-AND-SNAKE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SNAKE_SNAKE_EXP1.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SOUDARD.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SOUTH_PACIFIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SPACE_FIGHTER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SPACE_GUERILLA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SPACE_INVADERS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SPA_DATA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SQUASH_700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/STAR_FIGHTER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/STARTREK.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/STKEEPER2BAS700A.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/STRIP_POKER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUBMARINE_SHOOTER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUB-MONITOR-700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUICIDE_RUN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUPER-BANDIT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUPER_BIORHYTHM.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUPER_HELICOPTER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUPER_PUCK-MAN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUPER_SPY_OBJ.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUPERTYPEN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUPER_VRAC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUTAM1F.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUTAMC9.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUTAPEBA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SUTAPEMO.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/SYSTEME_EXPERT.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/TAPEWORM.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/TBASIC_BM_PK.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/T-BASIC_(UITLEG).${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/TELEFONTARIEVEN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/THREE_CARD_BRAG.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/TOMAHAWK.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/TRACKER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/TRANS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/TRUCKER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/TYPEN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/UFO.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/UNI700BASIC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/URANIA_II.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/URAS-700.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/VICIOUS_VIPER.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/VOL_676.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/VRAGENDMAKEN.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/WIZARD_CASTLE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/WONDERHOUSE.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/WOOKYA.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/WOOKYB.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/XANAGRAMS.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/XBC.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/XBC_F_1_02.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/YAMS.${SECTORSIZE}.bin:"
ROM_INCLUDE+="${MZB_PATH}/MZ-700/Z80_DESASSEMBLEUR.${SECTORSIZE}.bin:"
#ROM_INCLUDE+="${MZB_PATH}/MZ-700/ZEN.${SECTORSIZE}.bin:"

# Set the pointer which indicates the next ROM to be filled with applications.
GENROM=0

IFS=":"; for f in ${ROM_INCLUDE}
do
    if [ -f ${f} ]; then

        # Identify type of file.
        ${MZFTOOL} --command=IDENT --mzffile=${f} >/dev/null
        FILETYPE=$?

        if [ ${FILETYPE} == 1 ]; then

            # Fill the User ROM as these get listed first.
            if (( ${GENROM} == 0 )); then
                cat ${USER_ROM_I} "${f}" > /tmp/tmp.size
                FILESIZE=$(stat -c%s "/tmp/tmp.size")
                if (( ${FILESIZE} < 524288 )); then
                    echo "Adding $f to User I Rom"
                    cat "${f}" >> ${USER_ROM_I}
                    basename "${f}" .${SECTORSIZE}.bin >> ${ROM_LIST_FILE}
                else
                    GENROM=1
                fi
            fi

            if (( ${GENROM} == 1 )); then
                cat ${MONITOR_ROM} "${f}" > /tmp/tmp.size
                FILESIZE=$(stat -c%s "/tmp/tmp.size")
                if (( ${FILESIZE} < 524288 )); then
                    echo "Adding $f to Monitor Rom"
                    cat "${f}" >> ${MONITOR_ROM}
                    basename "${f}" .${SECTORSIZE}.bin >> ${ROM_LIST_FILE}
                else
                    GENROM=2
                fi
            fi

            # User ROM II and III are optional.
            if (( ${GENROM} == 2 )); then
                cat ${USER_ROM_II} "${f}" > /tmp/tmp.size
                FILESIZE=$(stat -c%s "/tmp/tmp.size")
                if (( ${FILESIZE} < 524288 )); then
                    echo "Adding $f to User II Rom"
                    cat "${f}" >> ${USER_ROM_II}
                    basename "${f}" .${SECTORSIZE}.bin >> ${ROM_LIST_FILE}
                else
                    GENROM=3
                fi
            fi

            if (( ${GENROM} == 3 )); then
                cat ${USER_ROM_III} "${f}" > /tmp/tmp.size
                FILESIZE=$(stat -c%s "/tmp/tmp.size")
                if (( ${FILESIZE} < 524288 )); then
                    echo "Adding $f to User III Rom"
                    cat "${f}" >> ${USER_ROM_III}
                    basename "${f}" .${SECTORSIZE}.bin >> ${ROM_LIST_FILE}
                else
                    GENROM=4
                fi
            fi

            if (( ${GENROM} == 4 )); then
                echo "Limit reached ROMS full, skipping from ${f}..."
                break
            fi
        else
            echo "File:${f},Type:${FILETYPE} is not machine code, skipping.."
        fi
    else
        echo "ALERT! File:${f} not found."
    fi
done
if [ -f ${USER_ROM_I} ]; then
    mv ${USER_ROM_I} ${ROM_PATH}/USER_ROM_${SECTORSIZE}.bin
    FILESIZE=$(stat -c%s "${ROM_PATH}USER_ROM_${SECTORSIZE}.bin")
    echo "USER ROM I SIZE (${ROM_PATH}USER_ROM_${SECTORSIZE}.bin) = ${FILESIZE} Bytes"
fi
if [ -f ${USER_ROM_II} ]; then
    mv ${USER_ROM_II} ${ROM_PATH}/USER_ROM_II_${SECTORSIZE}.bin
    FILESIZE=$(stat -c%s "${ROM_PATH}USER_ROM_II_${SECTORSIZE}.bin")
    echo "USER ROM II SIZE (${ROM_PATH}USER_ROM_II_${SECTORSIZE}.bin) = ${FILESIZE} Bytes"
fi
if [ -f ${USER_ROM_III} ]; then
    mv ${USER_ROM_III} ${ROM_PATH}/USER_ROM_III_${SECTORSIZE}.bin
    FILESIZE=$(stat -c%s "${ROM_PATH}USER_ROM_III_${SECTORSIZE}.bin")
    echo "USER ROM III SIZE (${ROM_PATH}USER_ROM_III_${SECTORSIZE}.bin) = ${FILESIZE} Bytes"
fi
if [ -f ${MONITOR_ROM} ]; then
    mv ${MONITOR_ROM} ${ROM_PATH}/MROM_${SECTORSIZE}.bin
    FILESIZE=$(stat -c%s "${ROM_PATH}/MROM_${SECTORSIZE}.bin")
    echo "MROM SIZE (${ROM_PATH}/MROM_${SECTORSIZE}.bin) = ${FILESIZE} Bytes"
fi
exit 0
